# Generated by Django 2.1.5 on 2021-08-03 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_friend'),
    ]

    operations = [
        migrations.CreateModel(
            name='likedCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Category')),
                ('likedcats', models.ManyToManyField(related_name='likedcats', to='rango.UserProfile')),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.UserProfile')),
            ],
        ),
    ]
