# Generated by Django 2.1.5 on 2021-08-03 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_likedcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rango.Category'),
        ),
    ]
