# Generated by Django 2.1.5 on 2021-08-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0011_remove_likedcat_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcat',
            name='likedcats',
            field=models.ManyToManyField(null=True, related_name='likedcats', to='rango.Category'),
        ),
    ]
