# Generated by Django 2.1.5 on 2021-08-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0012_auto_20210804_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedcat',
            name='likedcats',
            field=models.ManyToManyField(related_name='likedcats', to='rango.Category'),
        ),
    ]
